"""empty message

Revision ID: 361b67855546
Revises: 8b348cb5fa6c
Create Date: 2022-08-02 17:34:33.150633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361b67855546'
down_revision = '8b348cb5fa6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('altura', sa.String(length=250), nullable=False),
    sa.Column('personalidad', sa.String(length=250), nullable=False),
    sa.Column('genero', sa.String(length=250), nullable=False),
    sa.Column('características', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forma', sa.String(length=250), nullable=False),
    sa.Column('características', sa.String(length=80), nullable=False),
    sa.Column('especies_que_habitan', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('personajes_id', sa.Integer(), nullable=False),
    sa.Column('planetas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personajes_id'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['planetas_id'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'personajes_id', 'planetas_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    op.drop_table('planetas')
    op.drop_table('personajes')
    op.drop_table('favorito')
    # ### end Alembic commands ###
