"""empty message

Revision ID: a00b2f0d320a
Revises: 361b67855546
Create Date: 2022-08-03 20:20:16.704270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a00b2f0d320a'
down_revision = '361b67855546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('personajes_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planetas_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['personajes_id'], ['personajes.id'], name='favoritos_ibfk_1'),
    sa.ForeignKeyConstraint(['planetas_id'], ['planetas.id'], name='favoritos_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favoritos_ibfk_3'),
    sa.PrimaryKeyConstraint('user_id', 'personajes_id', 'planetas_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
